[package]
name = "nlos-process"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
nlos-types = { path = "../nlos-types" }
rusqlite.workspace = true
sha2.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal"] }

[lints]
workspace = true
